"""empty message

Revision ID: 705173261982
Revises: 
Create Date: 2023-05-08 05:18:50.330011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705173261982'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=140), nullable=True))
        batch_op.drop_column('client')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
